<a href="https://colab.research.google.com/github/MaheeshaSawandi/Safehood/blob/Prediction-Model/Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file_path = "/content/drive/MyDrive/SafeHood_ML/Dataset//dataset.xlsx"

df = pd.read_excel(file_path)

In [ ]:
df.head()

     Crime Types       Date      Time Gang  Age Gender      Location
0         Murder 2016-01-01  10:10:00   No   49      F  Doramadalawa
1  Housebreaking 2016-01-01  17:00:00   No   35      F    Kasamaduwa
2         Murder 2016-01-01  10:10:00   No   49      F  Doramadalawa
3         Murder 2016-01-01  10:10:00   No   49      F  Doramadalawa
4         Murder 2016-01-01  10:10:00   No   49      F  Doramadalawa

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87432 entries, 0 to 87431
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Crime Types  87432 non-null  object
 1   Date         87432 non-null  datetime64[ns]
 2   Time         87432 non-null  object
 3   Gang         87432 non-null  object
 4   Age          87432 non-null  int64
 5   Gender       87432 non-null  object
 6   Location     87432 non-null  object
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 4.7+ MB

In [ ]:
print("Rows and Columns:")
print(df.shape)

Rows and Columns:
(87432, 7)

In [ ]:
df.isnull().sum()

Crime Types    0
Date           0
Time           0
Gang           0
Age            0
Gender         0
Location       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(10347)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.dtypes

Crime Types            object
Date           datetime64[ns]
Time                   object
Gang                   object
Age                     int64
Gender                 object
Location               object
dtype: object

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])

In [ ]:
df["Time"] = (
    df["Time"]
    .astype(str)
    .str.replace("|", "", regex=False)
)

df["Time"] = pd.to_datetime(
    df["Time"],
    errors="coerce"
)

/tmp/ipykernel_1103/2686742057.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Time"] = pd.to_datetime(

In [ ]:
print(df["Crime Types"].nunique())

40

In [ ]:
crime_mapping = {

"Assault with dish": "Assault with Dish",

"Arson / causing damage with explosives":
"Arson / Causing damage with explosive",

"Fraud / breach of trust > LKR 100,000":
"Fraud / Breach of trust > LKR 100,000",

"Fraud / breach of trust > LKR 500,000":
"Fraud / Breach of trust > LKR 500,000",

"Fraud/Human trafficking":
"Fraud / Human trafficking",

"Keeping Heroin,Cocaine,Morphine production":
"Keeping Heroin, Cocaine, Morphine production",

"Obstruction of a police officer’s duty":
"Obstruction of a police officer's duty",

"Offenses under the oppressive weapons act":
"Offenses under the Oppressive Weapons act",

"Printing/ possession of counterfeit notes":
"Printing / Possession of counterfeit notes",

"Theft of plantation meterials > LKR 50,000":
"Theft of plantation materials > LKR 50,000",

"Unnatural offenses / Serious sexual abuse":
"Unnatural offence/Serious sexual abuse"

}

In [ ]:
df["Crime Types"] = df["Crime Types"].replace(crime_mapping)

In [ ]:
print(df["Crime Types"].nunique())

29

In [ ]:
df = df.drop_duplicates()

In [ ]:
print(df.shape)

print(df["Crime Types"].nunique())

df["Crime Types"].value_counts()

(77085, 7)
29

Crime Types
Housebreaking                                   4154
Theft of property > LKR 50,000                  3469
Keeping Heroin, Cocaine, Morphine production    3094
The loot                                        2928
Serious injury                                  2874
Assault with Dish                               2848
Fraud / Breach of trust > LKR 500,000           2793
Rape < age 16                                   2719
Statutory rape > age 16                         2704
Theft of cows > LKR 50,000                      2647
Unnatural offence/Serious sexual abuse          2551
Damage > LKR 25,000                             2548
Murder                                          2525
Theft of plantation materials > LKR 50,000      2525
Illegal riot                                    2525
Fraud / Breach of trust > LKR 100,000           2524
Abuse                                           2497
Arson / Causing damage with explosive           2484
Forcible acquisition                            2462
Sexual abuse of children                        2432
Obstruction of a police officer's duty          2429
Attempted Murder                                2428
Fraud / Human trafficking                       2424
Cruel treatment of children                     2424
Offenses under the Oppressive Weapons act       2420
Printing / Possession of counterfeit notes      2417
Kidnapping                                      2414
Anti-government activities                      2413
Possession of an automatic / repeater gun       2413
Name: count, dtype: int64

In [ ]:
df["Location"] = df["Location"]

In [ ]:
print(df["Location"].nunique())

68

In [ ]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day

In [ ]:
df["Hour"] = df["Time"].dt.hour

In [ ]:
df[df.duplicated()].head(10)

Empty DataFrame
Columns: [Crime Types, Date, Time, Gang, Age, Gender, Location, Year, Month, Day, Hour]
Index: []

In [ ]:
df["Time"].head()

0    2026-08-03 10:10:00
1    2026-08-03 17:00:00
11   2026-08-03 17:20:00
18   2026-08-03 19:00:00
20   2026-08-03 08:15:00
Name: Time, dtype: datetime64[ns]

In [ ]:
df["Time"].dtype

dtype('<M8[ns]')

In [ ]:
df["Time"] = pd.to_datetime(df["Time"])

In [ ]:
df["Hour"] = df["Time"].dt.hour

In [ ]:
df[["Time","Hour"]].head()

                  Time  Hour
0  2026-08-03 10:10:00  10.0
1  2026-08-03 17:00:00  17.0
11 2026-08-03 17:20:00  17.0
18 2026-08-03 19:00:00  19.0
20 2026-08-03 08:15:00   8.0

In [ ]:
severity_map = {

"Abuse":6,

"Kidnapping":10,

"Serious injury":9,

"Assault with Dish":8,

"Murder":10,

"Attempted Murder":10,

"Rape < age 16":10,

"Statutory rape > age 16":9,

"Unnatural offence/Serious sexual abuse":9,

"Cruel treatment of children":9,

"Sexual abuse of children":10,

"Fraud / Human trafficking":9,

"Obstruction of a police officer's duty":4,

"Illegal riot":7,

"Arson / Causing damage with explosive":9,

"Damage > LKR 25,000":3,

"Housebreaking":5,

"The loot":6,

"Forcible acquisition":8,

"Fraud / Breach of trust > LKR 500,000":4,

"Fraud / Breach of trust > LKR 100,000":3,

"Theft of plantation materials > LKR 50,000":2,

"Theft of cows > LKR 50,000":2,

"Theft of property > LKR 50,000":3,

"Printing / Possession of counterfeit notes":6,

"Anti-government activities":8,

"Offenses under the Oppressive Weapons act":8,

"Possession of an automatic / repeater gun":9,

"Keeping Heroin, Cocaine, Morphine production":8

}

In [ ]:
df["Crime_Severity_Score"] = df["Crime Types"].map(severity_map)

In [ ]:
df["Crime_Severity_Score"].isnull().sum()

np.int64(0)

In [ ]:
df["Crime_Severity_Score"].value_counts().sort_index()

Crime_Severity_Score
2      5172
3      8541
4      5222
5      4154
6      7842
7      2525
8     13237
9     17874
10    12518
Name: count, dtype: int64

In [ ]:
df.head()

,Crime Types,Date,Time,Gang,Age,Gender,Location,Year,Month,Day,Hour,Crime_Severity_Score
0,Murder,2016-01-01,2026-08-03 10:10:00,No,49,F,Doramadalawa,2016,1,1,10.0,10
1,Housebreaking,2016-01-01,2026-08-03 17:00:00,No,35,F,Kasamaduwa,2016,1,1,17.0,5
11,The loot,2016-01-01,2026-08-03 17:20:00,No,27,F,Mihintale,2016,1,1,17.0,6
18,"Keeping Heroin, Cocaine, Morphine production",2016-01-03,2026-08-03 19:00:00,No,26,M,Wellaragama,2016,1,3,19.0,8
20,Housebreaking,2016-01-03,2026-08-03 08:15:00,No,44,M,Rambawa,2016,1,3,8.0,5

In [ ]:
monthly = df.groupby(
    [
        "Location",
        "Year",
        "Month"
    ]
).agg(
    Crime_Count=("Crime Types","count"),
    Average_Severity=("Crime_Severity_Score","mean"),
    Maximum_Severity=("Crime_Severity_Score","max")
).reset_index()

In [ ]:
monthly.head()

     Location  Year  Month  Crime_Count  Average_Severity  Maximum_Severity
0  Abhayapura  2016      1           26          6.846154                10
1  Abhayapura  2016      2           33          6.606061                10
2  Abhayapura  2016      3           19          7.157895                10
3  Abhayapura  2016      4           21          7.000000                10
4  Abhayapura  2016      5           15          6.000000                10

In [ ]:
monthly = monthly.sort_values(
    [
        "Location",
        "Year",
        "Month"
    ]
)

In [ ]:
monthly["Next_Month_Crime"] = (
    monthly
    .groupby("Location")["Crime_Count"]
    .shift(-1)
)

In [ ]:
def risk_label(x):

    if x <= 10:
        return "Low"

    elif x <= 30:
        return "Medium"

    else:
        return "High"


monthly["Future_Risk"] = monthly["Next_Month_Crime"].apply(risk_label)

In [ ]:
monthly["Future_Risk"].value_counts()

Future_Risk
Medium    2737
Low       2557
High       344
Name: count, dtype: int64

In [ ]:
df["Hour"].head()

0     10.0
1     17.0
11    17.0
18    19.0
20     8.0
Name: Hour, dtype: float64

In [ ]:
monthly.shape

(5638, 8)

In [ ]:
monthly.head()

,Location,Year,Month,Crime_Count,Average_Severity,Maximum_Severity,Next_Month_Crime,Future_Risk
0,Abhayapura,2016,1,26,6.846154,10,33.0,High
1,Abhayapura,2016,2,33,6.606061,10,19.0,Medium
2,Abhayapura,2016,3,19,7.157895,10,21.0,Medium
3,Abhayapura,2016,4,21,7.000000,10,15.0,Medium
4,Abhayapura,2016,5,15,6.000000,10,28.0,Medium

In [ ]:
monthly.to_excel(
    "processed_dataset.xlsx",
    index=False
)

In [ ]:
df.to_excel(
    "cleaned_dataset.xlsx",
    index=False
)

In [ ]:
df.to_excel(
    "/content/drive/MyDrive/SafeHood_ML/Dataset/cleaned_dataset.xlsx",
    index=False
)

In [ ]:
monthly.to_excel(
    "/content/drive/MyDrive/SafeHood_ML/Dataset/processed_dataset.xlsx",
    index=False
)